//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceTrackingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrackingDeviceMaster
    {
        public int Id { get; set; }
        public string DriverId { get; set; }
        public int MaxSpeed { get; set; }
        public string DeviceSerial { get; set; }
        public string FirmWareVersion { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string EW { get; set; }
        public string NS { get; set; }
        public string Heading { get; set; }
    }
}
